### ISSUE TITLE
remove unmaintained tracker code

### ISSUE THREAD

**Issue by stevemar** [raheelzubairy/Real-Time-Payments-FTM#1]
The metrics tracker project is no longer maintained.

Remove the following:

- [ ] Badge at top of README
- [ ] Privacy Notice from Readme
- [ ] Disabling Deployment Tracking from Readme
- [ ] Use of metric tracker in app, i.e. `require('metrics-tracker-client').track();`
- [ ] The metrics-tracker library from requirement.txt or package.json
- [ ] The `repository.yml` file at the app level

Update the `deploy to ibm cloud` button to use this image: https://bluemix.net/deploy/button.png

See https://github.com/IBM/watson-conversation-slots-intro/pull/71/files as an example

**Comment by ljbennett62** [comment]
@stevemart - it looks like this was corrected - can you close out your issue?  tx

**Comment by stevemar** [comment]
yes, done in https://github.com/IBM/real-time-payments/commit/8f9aa4fe5fcd0329397c13025c375c6e71a46be1
